#workflow name
name: Hello

#runs on trigger
on: workflow_dispatch

jobs:
#jobs in workflow
  greet:
#runners in workflow
    runs-on: ubuntu-latest


    steps:
      - name: say hello to user
        run: echo "Hello sid"

      - name: say hello to user
        run: echo "hello $USER"

      
